In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

np.int64(8)

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
part_arr = arr[0:6]

In [12]:
part_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
part_arr[:] = 99

In [14]:
part_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

In [17]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy[0:5] = 20

In [19]:
arr_copy

array([20, 20, 20, 20, 20, 99,  6,  7,  8,  9, 10])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[2]

array([35, 40, 45])

In [24]:
arr_2d[2][1]

np.int64(40)

In [25]:
arr_2d[1,0]

np.int64(20)

In [26]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [27]:
arr_2d[:2,1]

array([10, 25])

In [28]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
arr_2d[:,2]

array([15, 30, 45])

In [33]:
arr = np.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [36]:
bool_arr = arr > 5

In [37]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [38]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [39]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [40]:
x = 2
arr[arr < x]

array([1])

In [41]:
arr_2d = np.arange(50).reshape(5,10)

In [42]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [43]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [44]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])