In [1]:
import numpy as np
#import numpy

In [2]:
my_list = [1,2,3]
#basic list

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)
#create a numpy array out of a list

array([1, 2, 3])

In [5]:
matrix = [[1,2,3],[4,5,6]]
#define a matrix

In [6]:
matrix

[[1, 2, 3], [4, 5, 6]]

In [7]:
np.array(matrix)
#convert matrix to numpy array

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.arange(1,10)
#create numbers in range 1 to 9 (10 is exclusive)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10,2)
#create numbers in range 1 to 9 in steps of 2

array([1, 3, 5, 7, 9])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
np.zeros(4)
#create a array of zeroes

array([0., 0., 0., 0.])

In [12]:
np.zeros((5,5))
#create a matrix of zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((10,10))
#create a matrix of ones 10 by 10

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,10)
#linear distribute numbers between 0 to 10

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
np.linspace(0,10,3)
#linear distribute with 3 steps

array([ 0.,  5., 10.])

In [16]:
np.eye(5)
#unit matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(2)
#create a array of random numbers

array([0.85922977, 0.45521405])

In [18]:
np.random.rand(10)
#create 10 random numbers

array([0.81462705, 0.61319922, 0.7517623 , 0.03230814, 0.41239035,
       0.26916315, 0.58363326, 0.15045863, 0.46194159, 0.84449008])

In [22]:
np.random.rand(2,2)
#create a matrix of random numbers

array([[0.38759731, 0.04096115],
       [0.59599468, 0.65257881]])

In [23]:
np.random.randint(1,100,5)


array([12, 15, 88, 55, 90])

In [24]:
np.random.randint(1,100)

67

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0, 50, 10)

In [28]:
ranarr

array([ 7, 28, 44, 32, 17, 30, 30, 24, 13, 31])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([ 7, 28, 44, 32, 17, 30, 30, 24, 13, 31])

In [31]:
ranarr.max()

np.int64(44)

In [33]:
ranarr.argmax()

np.int64(2)

In [34]:
ranarr.min()

np.int64(7)

In [35]:
ranarr.argmin()

np.int64(0)

In [36]:
arr.shape

(25,)

In [37]:
ranarr.shape

(10,)

In [38]:
ranmat = arr.reshape(5,5)

In [39]:
ranmat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranmat.shape

(5, 5)

In [41]:
ranmat.dtype

dtype('int64')

In [42]:
ranarr.dtype

dtype('int64')